# Generated by Django 6.0.2 on 2026-02-14 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Phone',
            new_name='phone',
        ),
    ]
